on:
  workflow_dispatch:
    branches:
      - main

name: Terraform CLI

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.6"
      - name: Terraform Init
        id: init
        run: terraform init              \
      - name: Terraform validate
        id: validate
        run: terraform validate   