on:
  workflow_dispatch:
    branches:
      - main

name: Terraform CLI Workflow - Init Validate Plan and Apply

jobs:
  terraforminitvalidateandplan:
    name: "Terraform Init Validate Plan and Apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.6.6"
      - name: Terraform Init
        id: init
        run: | 
          terraform init \
          -backend-config="access_key=${{ secrets.TF_VAR_AWS_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.TF_VAR_AWS_SECRET_KEY }}" 
      - name: Package lambda code into zip file
        run: |
          cd apilambda
          pwd
          pip install -r ./requirements.txt -t .
          zip -r ../lambda.zip .
          cd ..      
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Terraform plan
        id: plan
        run: |
          terraform plan \
            -var="aws_access_key=${{ secrets.TF_VAR_AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.TF_VAR_AWS_SECRET_KEY }}" \
            -input=false \
            -out=tfplan
      - name: Check location of plan output file
        id: checkfilelocation
        run: ls -R .
      - name: Upload Plan Artifact
        id: uploadplanartifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./tfplan
      # - name: Wait for approval to run apply
      #   id: manualapprovalforapply
      #   uses: trstringer/manual-approval@v1
      #   with:
      #     secret: ${{ secrets.MANUALAPPROVALSECRET }}
      #     approvers: fakhtar
      #     minimum-approvals: 1
      #     issue-title: "Approve Apply"
      #     issue-body: "Please approve to apply infrastrcutre"
      - name: Echo approved
        id: echoapproved
        run: echo "approved"
      - name: Display structure of directory
        run: ls -R
      - name: Terraform apply
        id: apply
        run: |
          terraform apply \
            -input=false \
            -auto-approve \
            -lock=false \
            tfplan